syntax = "proto3";

package user;
option go_package="./user";

message UserRegisterReq {
  string username = 1;
  string password = 2;
}

message UserRegisterResp {
  bool is_success = 1;
}

message UserLoginReq {
  string username = 1;
  string password = 2;
}

message UserLoginResp {
  bool is_success = 1;
}

message RefreshTokenReq {}

// 
service User {
  // 注册
  rpc UserRegister(UserRegisterReq) returns (UserRegisterResp);

  // 登录
  rpc UserLogin(UserLoginReq) returns (UserLoginResp);

  // 刷新 Token
  rpc RefreshToken(RefreshTokenReq) returns (UserLoginResp);
}
