// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: user.proto

package userclient

import (
	"context"

	"ReelFlow/rpc/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RefreshTokenReq  = user.RefreshTokenReq
	UserLoginReq     = user.UserLoginReq
	UserLoginResp    = user.UserLoginResp
	UserRegisterReq  = user.UserRegisterReq
	UserRegisterResp = user.UserRegisterResp

	User interface {
		// 注册
		UserRegister(ctx context.Context, in *UserRegisterReq, opts ...grpc.CallOption) (*UserRegisterResp, error)
		// 登录
		UserLogin(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginResp, error)
		// 刷新 Token
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*UserLoginResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 注册
func (m *defaultUser) UserRegister(ctx context.Context, in *UserRegisterReq, opts ...grpc.CallOption) (*UserRegisterResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UserRegister(ctx, in, opts...)
}

// 登录
func (m *defaultUser) UserLogin(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UserLogin(ctx, in, opts...)
}

// 刷新 Token
func (m *defaultUser) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*UserLoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}
