// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type Message struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type RefreshTokenReq struct {
}

type UserLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	Message
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type UserRegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserRegisterResp struct {
	Message
	IsSuccess bool `json:"is_success"`
}
